[tasks.deploy]
description = "Build the binary and link it to user bin dir"
run = """
echo Build and move to system binaries
go build -o themectl
sudo mv -f themectl /usr/local/bin/themectl
themectl completion fish > ~/.config/fish/completions/themectl.fish
"""

[tasks.test]
description = "Run Tests"
run = """
echo Running tests...
gotestsum ./...
"""

[tasks."gen:schema"]
description = "Generate JSON schema from go stucts"
run = """
echo gen schemas...
go generate ./...
"""

[tasks.check-schemas]
description = "Regenerate JSON schemas and fail on drift"
run = """
go generate ./...
git diff --exit-code schemas/
"""

[tools]
"go:gotest.tools/gotestsum" = "latest"
